// Downloads the two brand faces from Google Fonts and self-hosts them.
//
//   node scripts/build-fonts.mjs           download woff2 + write the @font-face partial
//   node scripts/build-fonts.mjs --check   download nothing, exit 1 if a file is missing
//
// Why self-host at all: the Google Fonts stylesheet is a render-blocking
// request to a third party, and the page's LCP element is the hero headline —
// text that cannot paint in its real face until that round trip finishes.
// Lighthouse measured 1,140 ms of render-blocking on that alone. Served from
// the same origin the browser already has a connection to, and preloaded, the
// font arrives inside the first round trip instead of after three.
//
// Variable faces, one file per family per subset: `wght@400..700` covers every
// weight the site uses (400, 500, 600, 700) in a single download, where the
// static cut would be four.
//
// Only latin and latin-ext are kept. The site is English and Spanish; cyrillic,
// greek and vietnamese are ~60% of what Google would serve and no page can
// render a character from them.

import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { FONT_FAMILIES as FAMILIES, FONT_SUBSETS as SUBSETS, fontFiles } from './site.config.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, 'assets', 'fonts');
const PARTIAL = join(ROOT, 'scss', 'base', '_fonts.scss');
const check = process.argv.includes('--check');

// Google serves woff2 only to a browser that says it can take it. With Node's
// default agent the same URL answers with truetype, which is roughly twice the
// bytes for no gain.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Instrument+Sans:wght@400..700&family=Inter:wght@400..700&display=swap';

// Which families, which subsets and which of them get preloaded all live in
// site.config.mjs: build-i18n.mjs writes the preload tags and must not import
// this file to learn their names — everything below runs on import.

if (check) {
  const missing = fontFiles().filter(f => !existsSync(join(ROOT, f)));
  if (!existsSync(PARTIAL)) missing.push('scss/base/_fonts.scss');
  if (missing.length) {
    console.error(`build-fonts: ${missing.length} file(s) missing — run npm run build:fonts`);
    for (const m of missing) console.error(`  · ${m}`);
    process.exit(1);
  }
  console.log('build-fonts: every font present.');
  process.exit(0);
}

const css = await fetch(CSS_URL, { headers: { 'User-Agent': UA } }).then(r => {
  if (!r.ok) throw new Error(`build-fonts: Google Fonts answered ${r.status}`);
  return r.text();
});

// Each block is preceded by a /* subset */ comment, which is the only place the
// subset name appears — the URL itself is an opaque hash.
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g)].map(m => ({
  subset: m[1],
  body: m[2],
}));

const field = (body, name) => (body.match(new RegExp(`${name}:\\s*([^;]+);`)) || [])[1]?.trim();

mkdirSync(OUT_DIR, { recursive: true });

const faces = [];
for (const { subset, body } of blocks) {
  if (!SUBSETS.includes(subset)) continue;

  const family = (field(body, 'font-family') || '').replace(/['"]/g, '');
  const slug = FAMILIES[family];
  if (!slug) continue;

  const url = (field(body, 'src') || '').match(/url\((\S+?)\)/)?.[1];
  if (!url) throw new Error(`build-fonts: no woff2 url for ${family} ${subset}`);

  const file = `${slug}-${subset}.woff2`;
  const bytes = Buffer.from(await fetch(url, { headers: { 'User-Agent': UA } }).then(r => r.arrayBuffer()));
  writeFileSync(join(OUT_DIR, file), bytes);
  console.log(`build-fonts: assets/fonts/${file}  ${(bytes.length / 1024).toFixed(1)} KB`);

  faces.push({ family, file, weight: field(body, 'font-weight'), range: field(body, 'unicode-range') });
}

if (!faces.length) throw new Error('build-fonts: Google Fonts returned no matching face');

// The url is relative to the stylesheet, not to the document, so one path works
// for the pages at the root and for their twins one level down in es/.
const partial = `// GENERATED by scripts/build-fonts.mjs — do not edit by hand.
//
// Self-hosted so the faces come from the origin the browser is already talking
// to. Variable files: one download per family per subset covers 400–700.
//
// \`swap\`, deliberately: the fallback stack in the family tokens is metrically
// close enough that the reflow is small, and a blocked first paint costs more
// than a swap. Preload lives in the generated <head> block, see build-i18n.mjs.

${faces
  .map(
    f => `@font-face {
  font-family: "${f.family}";
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url("../assets/fonts/${f.file}") format("woff2");
  unicode-range: ${f.range};
}`,
  )
  .join('\n\n')}
`;

writeFileSync(PARTIAL, partial, 'utf8');
console.log(`build-fonts: scss/base/_fonts.scss  (${faces.length} faces)`);
