// What the site publishes about itself.
//
// Read by build-i18n.mjs (the generated <head> block), build-seo.mjs (sitemap
// and robots.txt) and build-og.mjs (the social cards). The origin, the page
// list and the identity are declared once here so the three generators cannot
// drift apart — a canonical URL that disagrees with the sitemap is the classic
// way a static site loses its indexing.

export const BASE = 'https://pizarradas.github.io/portfolio';

// Identity for the Person / ProfilePage graph. Everything here is already
// public on the page itself, and the email is the professional one — BRAND.md
// §6 forbids the personal address anywhere on the site.
export const SITE = {
  name: 'José Luis Pizarro',
  legalName: 'José Luis Pizarro Feo',
  jobTitle: 'Product Designer & Front-End Engineer',
  email: 'profesional.pizarro@gmail.com',
  locality: 'Madrid',
  country: 'ES',
  sameAs: ['https://www.linkedin.com/in/joseluispizarrofeo'],
  // Claims the site actually backs with a case, not a keyword list.
  knowsAbout: [
    'Design Systems',
    'Design Tokens',
    'Front-End Engineering',
    'SCSS Architecture',
    'Editorial Product Design',
    'Web Accessibility (WCAG 2.1 AA)',
    'AI-assisted Development',
  ],
  siteName: { en: 'José Luis Pizarro — Portfolio', es: 'José Luis Pizarro — Portfolio' },
};

// Every page that exists in both languages. Order is the crawl order in the
// sitemap and, on the home page, the order of the argument (BRAND.md §1).
//
//   ogType   — profile for the person, article for a case study
//   schema   — the schema.org @type of the page's main entity
//   priority — sitemap hint, relative within this site only
//   crumb    — BreadcrumbList label, per language
export const PAGES = [
  {
    file: 'index.html',
    ogType: 'profile',
    schema: 'ProfilePage',
    priority: '1.0',
    crumb: { en: 'Home', es: 'Inicio' },
  },
  {
    file: 'case-42ds.html',
    ogType: 'article',
    schema: 'CreativeWork',
    priority: '0.9',
    crumb: { en: '42DS', es: '42DS' },
  },
  {
    file: 'case-sport.html',
    ogType: 'article',
    schema: 'CreativeWork',
    priority: '0.8',
    crumb: { en: 'SPORT Mobile Cards', es: 'Tarjetas móviles de SPORT' },
  },
  {
    file: 'case-map.html',
    ogType: 'article',
    schema: 'CreativeWork',
    priority: '0.8',
    crumb: { en: 'Interactive Media Map', es: 'Mapa interactivo de medios' },
  },
  {
    file: 'case-worldcup.html',
    ogType: 'article',
    schema: 'CreativeWork',
    priority: '0.8',
    crumb: { en: 'World Cup 2026', es: 'Mundial 2026' },
  },
  {
    file: 'case-atlas.html',
    ogType: 'article',
    schema: 'CreativeWork',
    priority: '0.8',
    crumb: { en: 'ATLAS × SYX', es: 'ATLAS × SYX' },
  },
  {
    file: 'case-illustrations.html',
    ogType: 'article',
    schema: 'CreativeWork',
    priority: '0.7',
    crumb: { en: 'SPORT Illustrations', es: 'Ilustraciones de SPORT' },
  },
];

export const PAGE_FILES = PAGES.map(p => p.file);
export const PAGE_BY_FILE = new Map(PAGES.map(p => [p.file, p]));

// One card per page, generated by build-og.mjs from the page's own headline.
export const ogImage = file => `assets/og/${file.replace(/\.html$/, '')}.png`;
export const OG_IMAGE_SIZE = { width: 1200, height: 630 };

/* ------------------------------------------------------------ html scraping */

// The English pages are the source of truth for copy, so the head generator and
// the card generator read the headline out of the markup instead of keeping a
// second copy of it here. Regex, not a parser: build-i18n already treats these
// files as a token stream, and a tree would have to be re-serialised.

const decode = s =>
  s
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");

const stripTags = s => s.replace(/<[^>]*>/g, '');
const squash = s => s.replace(/\s+/g, ' ').trim();

/** Raw <title>, entities intact — safe to drop straight into an attribute. */
export function titleOf(html) {
  const m = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  return m ? squash(m[1]) : '';
}

/** Content of <meta name="description">, whatever order the attributes are in. */
export function descriptionOf(html) {
  const tag = html.match(/<meta\b[^>]*\bname\s*=\s*"description"[^>]*>/i);
  if (!tag) return '';
  const content = tag[0].match(/\scontent\s*=\s*"([^"]*)"/i);
  return content ? squash(content[1]) : '';
}

/** First <h1>, tags removed. The page's real headline, already translated. */
export function headlineOf(html) {
  const m = html.match(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i);
  return m ? squash(stripTags(m[1])) : '';
}

/** First .atom-eyebrow — the kicker that sits above the headline. */
export function kickerOf(html) {
  const m = html.match(/<p\b[^>]*\bclass\s*=\s*"[^"]*\batom-eyebrow\b[^"]*"[^>]*>([\s\S]*?)<\/p>/i);
  return m ? squash(stripTags(m[1])) : '';
}

/** Same as the above, but decoded for use as JSON-LD text or rendered copy. */
export const plain = s => squash(decode(s));
